name: Compile source code

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: npm install
        env:
          CI: true

      - name: Run compile
        run: npm run compile

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Compile source code
