# This is a basic workflow to help you get started with Actions

name: Minify CSS

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    paths:
      - 'dist/sbuttons.css'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    minify:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{ github.head_ref }}
          - uses: actions/setup-node@v1
            with:
              node-version: "12.x"
          - name: Install
            run: npm install
            env:
                CI: true

          - name: Clean CSS
            run: npm run clean-css
            
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: Apply minification





